### ISSUE TITLE
TypeError: editor.currentSelection is not a function

### ISSUE THREAD

**Issue by enoversum** [noahbuscher/N1-Jiffy#10]
Hi there,

since the latest N1 version Jiffy throws out another error, which disappears immediately when I disable Jiffy. If you need any more info, please let me know :smile: .

Best

Eno

**Comment by bengotow** [comment]
Hey! This should be fixed by #11 :-)

**Comment by enoversum** [comment]
@bengotow Hey, sounds lovely :heart_decoration: !

**Comment by noahbuscher** [comment]
Hey, guys! 🎉 The PR was merged and dropped as the 0.1.9 release!

Download it [here](https://github.com/noahbuscher/N1-Jiffy/releases/tag/0.1.9).
