### ISSUE TITLE
Not working on Nylas Mail (1.0.15)

### ISSUE THREAD

**Issue by rubengarciam** [noahbuscher/N1-Jiffy#15]
`ReferenceError: Unknown plugin "transform-async-generator-functions" specified in "base" at 0, attempted to resolve relative to "/Users/ruben/.nylas-mail/packages/N1-Jiffy/lib"`

**Comment by benkahle** [comment]
I had the same issue in 1.0.15, but it appears to have been fixed as of 1.0.17.
