### ISSUE TITLE
broken :(

### ISSUE THREAD

**Issue by grinich** [noahbuscher/N1-Jiffy#5]
![popup](https://cloud.githubusercontent.com/assets/92417/12211390/73f41700-b615-11e5-8e17-1db0ea9ee2f9.gif)

**Comment by noahbuscher** [comment]
Odd! Perhaps the beta key has reached it's quota for the day. I will switch over to a separate key soon, but can you check in the console to see if there are any errors if you have time today?

**Comment by grinich** [comment]
Nothing that I could find. If you can fix this fast, I wanted to feature it in the newsletter that's going out asap.

**Comment by grinich** [comment]
oh wait it started working?

**Comment by grinich** [comment]
It's super super glitchy

**Comment by noahbuscher** [comment]
Seems to be an incompajtilibty with the latest version of N1... Will push fix as soon as possible.

**Comment by bengotow** [comment]
Hey @noahbuscher — this is an issue on our end, should be fixed in the next version!

**Comment by noahbuscher** [comment]
Awesome! Thank you.
